# ASSIGNMENT 7
### NUMPY
##### QUES1 - What is NumPy and what are its main advantages over regular Python lists? Coding Challenge:  Create a NumPy array from a list of numbers and perform basic arithmetic operations (addition, multiplication) on the array.
##### ANS1 - Numpy is a python library used for dealing with array 
##### Provides a powerful N-dimensional array object.
##### Faster and more memory-efficient than Python lists.

In [60]:
import numpy as np 

In [61]:
## creating array 
arr = np.array([1,2,3,4,5])
arr

## arithmetic operation 
arr1 = arr + 5
arr2 = arr *6 
print("your array is : ",arr)
print("after addition array is : ",arr1)
print("multiplied array is : ",arr2)

your array is :  [1 2 3 4 5]
after addition array is :  [ 6  7  8  9 10]
multiplied array is :  [ 6 12 18 24 30]


##### QUES2 - How can you create different types of arrays in NumPy, such as arrays filled with zeros, ones, or random values? Coding Challenge:  Write a Python script that creates a 3x3 array of zeros, a 3x3 array of ones, and a 3x3 array of random integers between 1 and 10.
##### ANS2 - Use np.zeros(), np.ones(), np.random for random arrays.

In [62]:
zeros = np.zeros((3, 3))
ones = np.ones((3, 3))
random = np.random.randint(1, 11, (3, 3))

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Random Integers 1-10:\n", random)


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Random Integers 1-10:
 [[ 8  8 10]
 [ 3  6  3]
 [ 2  6  3]]


##### QUES3 - Explain how array indexing and slicing work in NumPy. How does it differ from standard Python list indexing? Coding Challenge:  Create a 2D NumPy array and use slicing to extract a subarray from it. For example, extract a 2x2 subarray from a 4x4 array.
##### ANS3 - NumPy indexing works like lists but supports multi-dimensional arrays.
##### while slicing is powerful

In [63]:
arr = np.arange(16).reshape(4, 4)
print("Original 4x4:\n", arr)

subarray = arr[1:3, 1:3]  # Extract 2x2 from middle
print("2x2 Subarray:\n", subarray)

Original 4x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
2x2 Subarray:
 [[ 5  6]
 [ 9 10]]


##### QUES4 - What are some common functions in NumPy for performing statistical operations, such as mean, median, and standard deviation? Coding Challenge: Write a Python script that computes the mean, median, and standard deviation of a NumPy array containing 100 random values.
##### ANS4 - Common functions are : np.mean(), np.median(), np.std().

In [64]:
arr = np.array([1,2,3,4,5,6,7,8])
print("original array :",arr)

## statistical operation
np.mean(arr)
print("mean : ",np.mean(arr))
print("median : ",np.median(arr))
print("standard deviation : ",np.std(arr))

original array : [1 2 3 4 5 6 7 8]
mean :  4.5
median :  4.5
standard deviation :  2.29128784747792


##### QUES5 - How can you perform element-wise operations and matrix operations using NumPy? Provide examples of both. Coding Challenge: Create two 2D NumPy arrays and perform element-wise addition, subtraction, and matrix multiplication.
##### ANS5 - Element-wise: +, -, * (broadcasts element-wise).
##### Matrix: np.dot(), @ operator.

In [65]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Element-wise Addition:\n", A + B)
print("Element-wise Subtraction:\n", A - B)
print("Matrix Multiplication:\n", np.dot(A, B))


Element-wise Addition:
 [[ 6  8]
 [10 12]]
Element-wise Subtraction:
 [[-4 -4]
 [-4 -4]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


##### QUES6 - What are broadcasting and how does it work in NumPy? How can you use it to perform operations on arrays of different shapes? Coding Challenge:  Write a Python script that demonstrates broadcasting by adding a 1D array to each row of a 2D array.
##### ANS6 - Allows operations on arrays of different shapes.

In [66]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
arr1 = np.array([10, 20, 30])

result = arr + arr1  # b is broadcasted to each row of A

print("2D array:\n", arr)
print("1D array:\n", arr1)
print("Result of broadcasting:\n", result)


2D array:
 [[1 2 3]
 [4 5 6]]
1D array:
 [10 20 30]
Result of broadcasting:
 [[11 22 33]
 [14 25 36]]


##### QUES7 - How do you handle missing or NaN values in NumPy arrays? What functions or methods can be used for this purpose? Coding Challenge: Create a NumPy array with some NaN values and use NumPy functions to replace NaNs with the mean of the array.
##### ANS7 - Use np.isnan(), np.nanmean(), np.nan_to_num().

In [67]:
arr = np.array([1, 2, np.nan, 4, np.nan, 6])
print("Original:", arr)

mean_val = np.nanmean(arr)
arr[np.isnan(arr)] = mean_val

print("NaNs replaced with mean:", arr)

Original: [ 1.  2. nan  4. nan  6.]
NaNs replaced with mean: [1.   2.   3.25 4.   3.25 6.  ]


##### QUES8 - Explain the purpose and usage of NumPy's "reshape()" and "flatten()" methods. How can you change the shape of an array? Coding Challenge:  Write a Python script that creates a 1D array with 12 elements, reshapes it into a 3x4 array, and then flattens it back into a 1D array
##### ANS8 - reshape(): Change shape.
##### flatten(): Return a 1D copy.

In [68]:
arr = np.arange(12)
print("1D array:", arr)
## reshape
reshaped = arr.reshape(3, 4)
print("Reshaped to 3x4:\n", reshaped)
## flatten
flattened = reshaped.flatten()
print("Flattened back:", flattened)


1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped to 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened back: [ 0  1  2  3  4  5  6  7  8  9 10 11]


##### QUES9 - .  What is the role of "numpy.linalg" for linear algebra operations? How can you use it to perform operations like matrix inversion or eigenvalue computation? Coding Challenge:  Create a 2x2 matrix and use "numpy.linalg.inv()" to compute its inverse. Also, compute the eigenvalues and eigenvectors of the matrix.
##### ANS9 - For linear algebra: inversion, eigenvalues, etc.

In [69]:
matrix = np.array([[4, 2],[3, 1]])

inverse = np.linalg.inv(matrix)
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Matrix:\n", matrix)
print("Inverse:\n", inverse)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Matrix:
 [[4 2]
 [3 1]]
Inverse:
 [[-0.5  1. ]
 [ 1.5 -2. ]]
Eigenvalues: [ 5.37228132 -0.37228132]
Eigenvectors:
 [[ 0.82456484 -0.41597356]
 [ 0.56576746  0.90937671]]


##### QUES10 - How can you save and load NumPy arrays to and from files? What formats are supported? Coding Challenge:  Write a Python script that saves a NumPy array to a file using "numpy.save()" and then loads it back using "numpy.load()".
##### ANS10 - np.save() → .npy binary.
##### np.load() to read it back.

In [70]:
arr = np.array([1, 2, 3, 4, 5])

np.save('my_array.npy', arr)
loaded_arr = np.load('my_array.npy')

print("Original:", arr)
print("Loaded:", loaded_arr)


Original: [1 2 3 4 5]
Loaded: [1 2 3 4 5]
