# PYTHON LIBRARY
## numpy

In [53]:
## check numpy version
import numpy as np 
## 1D, 2D, 3D
np.__version__

'2.3.0'

In [54]:
lst = [1,2,3,4,5]
ar1 = np.array(lst)
ar1         ## print the list
## print(type(ar1))

## if multiple element is passes
ar1 = np.array([1,2,"3",4,5])
ar1    ## convert whole list into string 

array(['1', '2', '3', '4', '5'], dtype='<U21')

In [55]:
## when ypu have to create an array in a range 
ar2 = np.arange(1,10)
ar2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
## for matrix 0 and 1 
arr3 = np.ones(5)
arr3

## zeros
arr4 = np.zeros(4)
arr4

array([0., 0., 0., 0.])

#### 2D array as matrix

In [57]:
arr5 = np.zeros((2,3))
arr5        ## no of square bracket = dimension of array 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [58]:
arr6 = np.linspace(1,10,5) ## 1-10 range and want 5 number 
arr6

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [59]:
## print an array from 1-30 in 2D array
arr7 = np.arange(1,31).reshape(5,6)  ## (5,6) because no of elements we want should me equal to the given multiple of rows and column 
arr7

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [60]:
## random number array
# arr8 = np.random.randint(1,100,10)
arr8 = np.random.random(10)
arr8

array([0.36673909, 0.30365453, 0.77529152, 0.54002022, 0.66836027,
       0.77816266, 0.47210057, 0.39842912, 0.53291891, 0.16227319])

In [61]:
## 2D array of 60 element 
arr9 = np.arange(60).reshape(5,12)
print(arr9.shape)   ## about the shape 
print(arr9.dtype)   ## about datatype and bits
print(arr9.size)    ## size of array
print(arr9.ndim)    ## dimension 

(5, 12)
int64
60
2


In [62]:
## multidimension array covert id
print(arr9.ravel())
print(arr9.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59]


In [63]:
## transpose of an array 
arr9 = np.arange(60).reshape(5,12)
print(arr9.shape)
arr10 = arr9.T.shape
print(arr10)

(5, 12)
(12, 5)


In [64]:
## indexing and slicing 
## 1D array indexing and slicing is same as normal list and tuple slicing and indexing 
## INDEXING 
lst = [1,2,3,4,5]
ar1 = np.array(lst)
print(lst[3])

## SLICING 
lst = [1,2,3,4,5]
ar1 = np.array(lst)
print(lst[0:4])
print(lst[-5:-1])
print(lst[-1:-2])

## UPDATING 
lst = [1,2,3,4,5]
ar1 = np.array(lst)



4
[1, 2, 3, 4]
[1, 2, 3, 4]
[]


In [ ]:
# ## indexing and slicing in 2D array 
# ## 1D array
# ## 2D array --> [row start: row end: row skip, col start: col end : col skip]
arr9 = np.arange(60).reshape(5,12)
# print(arr9,"\n")

# ## indexing 
# print(arr9[3],"\n")

# ## slicing 
# print(arr9[3:6,2:3],"\n")
# print(arr9[3:4],"\n")
# print(arr9[3:6,2:],"\n")

## arr9[3:4,2:3] = 100
## arr9[::-1 , ::-1]

array([[59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48],
       [47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36],
       [35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0]])

### 3D array 

In [ ]:
## 2D array ki array hi 3D array hoti h 
arr10 = np.arange(225).reshape(3,15,5)
arr10

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141,

In [77]:
# arr = np.ones((3,4,5))
# print(arr,"\n")

# arr = np.zeros((2,2,3))
# print(arr,"\n")

arr = np.random.randint(1,100,225).reshape(3,15,5)
print(arr)


[[[95 67 22 81 23]
  [50 29 49 27 91]
  [73 73 90 15 72]
  [80 21 58 90 91]
  [43 81 34 51 12]
  [37 38 84 88 17]
  [63 74 78 67 15]
  [67 79 37 62 23]
  [20 65 34  6 91]
  [28 58 55 71 32]
  [ 2 38 89 62 32]
  [ 6 68 11 90 46]
  [27 59 41 94 70]
  [ 8 99 70 80 29]
  [86 59 32 12 12]]

 [[38 90 88 95 25]
  [38 86 98 92 54]
  [87 74 24 26 93]
  [63 37 76 17 72]
  [93 87 96 38 64]
  [12 28 82 92 40]
  [37 14 70 75 16]
  [77 47  2 12 61]
  [93 27 94 92 86]
  [53 34 79 90 48]
  [53 37 35 28 28]
  [40 52 76 34 29]
  [34 81 46 71 23]
  [52 76 61  2 97]
  [51 14 12  4 79]]

 [[90  2  2 85 99]
  [13 75 79 23  8]
  [35 99 70 91 43]
  [25  6  7 87 13]
  [62 27 12 21 34]
  [90 29 59 32 25]
  [46  3 93 31 11]
  [43 37 95 20 31]
  [44 66 88  1 57]
  [51 72 57  4 21]
  [11 47  4 24 13]
  [69 79 75 39 10]
  [47 83 46 36 67]
  [32 15 67 50 87]
  [96 65 46 26 76]]]


In [80]:
## slicing in 3D array 
## syntax - 
## [table start : table end : table skip, row_start: row_end : row_skip, col_start:column_end:col_skip]
arr[1]
arr[0:,1:4,2:4]

array([[[49, 27],
        [90, 15],
        [58, 90]],

       [[98, 92],
        [24, 26],
        [76, 17]],

       [[79, 23],
        [70, 91],
        [ 7, 87]]], dtype=int32)

In [94]:
# print(arr9)
# print(np.max(arr9))
# print(np.min(arr9))
# print(np.sum(arr9))
# print(np.median(arr9))
# print(np.mean(arr9))

# arr9.sort()
arr11 = np.array([2,5,1,9], ndmin = 3)
# arr11.argsort() ## sort by index number[1:2,2:0,5:1,9:3] 1 is at index 2 then 2 come first and so on 
arr11 * 2
arr11 + 2
arr11



array([[[2, 5, 1, 9]]])